[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "rbln-model-zoo"
version = "0.0.0"
requires-python = ">=3.10,<3.13"
dependencies = [
  "pyyaml>=6.0.1",
  "rich>=13.0.0",
  "tomli>=2.0; python_version < \"3.11\"",
  "typer>=0.9.0",
]

[project.scripts]
rbln-zoo = "rbln_zoo.cli:app"

[tool.setuptools]
packages = ["rbln_zoo"]
py-modules = []
